USE TASK3; 
DROP TABLE EMPLOYEES;
CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(50),
SALARY DECIMAL(10,2) 
);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY) VALUES
(1, 'ALEX', 'PANDIAN', 20000),
(2, 'BOB', 'MARLEY', 30000),
(3, 'DON', 'BOSCO', 35000),
(4, 'ZORO', 'RORONOA', 40000),
(5, 'JOHN', 'WICK', 20000); 
SELECT * FROM EMPLOYEES; 
DELIMITER //
CREATE FUNCTION GETBONUS(SALARY DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
DECLARE BONUS DECIMAL(10,2);
IF SALARY < 30000 THEN
SET BONUS = SALARY * 0.10;
ELSEIF SALARY >= 30000 AND SALARY <= 40000 THEN
SET BONUS = SALARY * 0.07;
ELSE 
SET BONUS = SALARY * 0.05;
END IF;
RETURN BONUS;
END;
// 
DELIMITER //
CREATE PROCEDURE GIVEBONUS(IN EMPID INT)
BEGIN
DECLARE CURRENTSALARY DECIMAL(10,2);
DECLARE BONUSAMOUNT DECIMAL(10,2);
SELECT SALARY INTO CURRENTSALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID =  EMPID;
SET BONUSAMOUNT = GETBONUS(CURRENTSALARY);
UPDATE EMPLOYEES 
SET SALARY = SALARY + BONUSAMOUNT
WHERE EMPLOYEE_ID = EMPID;
END;//
DELIMITER //
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY) VALUES
(6, 'JOHN', 'DOE', 5000.00);
CALL GIVEBONUS(1);
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 1;
CALL GIVEBONUS(3 AND 5);
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 3 OR EMPLOYEE_ID =5;